# -*- coding: utf-8 -*-
#
# Created by Alex Molina
# April 2020
# 
# This project is licensed under the MIT License - see the LICENSE file for details.
# Copyright (c) 2020 Alejandro Molina Villegas
import sys
import os
sys.path.append(os.path.join(os.path.dirname(__file__), ".", ".."))
from tmining.utils import covid19, covid19_symptoms, covid19_sampling, covid19_comorbidities, explore_dir
import re
import simplejson as json


class MedNotesMiner(object):
    """Medical notes data miner for Covid-19 insights"""
    def __init__(self, text_utf8, covid19_db=None, symptoms_db=None, sampling_db=None, morbidities_db=None):
        super(MedNotesMiner, self).__init__()
        self.wikidata_url = 'https://www.wikidata.org/wiki/'
        self.text = text_utf8
        self.clues = {'texto': self.text}
        self.lower_text = self.text.lower()
        if not covid19_db:
            self.covid19_db = covid19()
        if not symptoms_db:
            self.symptoms_db = covid19_symptoms()
        if not sampling_db:
            self.sampling_db = covid19_sampling()
        if not morbidities_db:
            self.morbidities_db = covid19_comorbidities()

    def check_covid19(self, lower_case=True):
        """match covid-19 mentions"""
        self.clues['COVID-19'] = {}

        # seek for covid matches
        for (covid_key, covid_name) in self.covid19_db:
            #TODO: method argumen contex_size
            regex = r'((\w+\W+){0,5}\b'+covid_name+r'\b(\W+\w+){0,5})'
            for covid_mention in re.finditer(regex, self.lower_text):
                context_mention = '...'+(covid_mention.groups()[0]).replace('\n', ' ')+'...'
                covid_info = {'mención':context_mention,
                              'wikidata': '{}{}'.format(self.wikidata_url, covid_key)}

                if not covid_name in self.clues['COVID-19']:
                    self.clues['COVID-19'][covid_name] = [covid_info]
                    continue

                self.clues['COVID-19'][covid_name].append(covid_info)

    def check_symptoms(self, lower_case=True):
        """match covid-19 symptoms"""
        self.clues['síntomas'] = {}

        # seek for symptoms matches
        for (sympt_key, sympt_name) in self.symptoms_db:
            #TODO: method argumen contex_size
            regex = r'((\w+\W+){0,5}\b'+sympt_name+r'\b(\W+\w+){0,5})'
            for sympt_mention in re.finditer(regex, self.lower_text):
                context_mention = '...'+(sympt_mention.groups()[0]).replace('\n', ' ')+'...'
                # NICETOHAVE: filter wikidata info selected
                # wikidict = get_entity_dict_from_api(sympt_key)
                # external_info = wikidict['claims'] if 'claims' in wikidict else ''
                sympt_info = {'descripción': sympt_name,
                              'mención':context_mention,
                              'wikidata': '{}{}'.format(self.wikidata_url, sympt_key)}

                if not sympt_key in self.clues['síntomas']:
                    self.clues['síntomas'][sympt_key] = [sympt_info]
                    continue

                self.clues['síntomas'][sympt_key].append(sympt_info)

    def check_comorbidities(self, lower_case=True):
        """match covid-19 comorbidities"""
        self.clues['comorbilidades'] = {}

        # seek for comorbidities matches
        for (comorbidity_key, comorbidity_name) in self.morbidities_db:
            #TODO: method argumen contex_size
            regex = r'((\w+\W+){0,5}\b'+comorbidity_name+r'\b(\W+\w+){0,5})'
            for morbid_mention in re.finditer(regex, self.lower_text):
                context_mention = '...'+(morbid_mention.groups()[0]).replace('\n', ' ')+'...'
                comorbidity_info = {'descripción': comorbidity_name,
                                    'mención':context_mention,
                                    'wikidata': '{}{}'.format(self.wikidata_url, comorbidity_key)}

                if not comorbidity_key in self.clues['comorbilidades']:
                    self.clues['comorbilidades'][comorbidity_key] = [comorbidity_info]
                    continue

                self.clues['comorbilidades'][comorbidity_key].append(comorbidity_info)

    def check_sampling(self):
        """match covid-19 sampling mentions"""
        self.clues['muestreos'] = []

        # seek for sampling matches
        for sampling_cueword in self.sampling_db:
            regex = r'((\w+\W+){0,5}\b'+sampling_cueword+r'\b(\W+\w+){0,5})'
            for samp_mention in re.finditer(regex, self.lower_text):
                context_mention = '...'+(samp_mention.groups()[0]).replace('\n', ' ')+'...'
                self.clues['muestreos'].append({'mención': context_mention})


class CovidJsonParser(object):
    """Parse JSON symptoms registers generated by MedNotesMiner"""
    def __init__(self, columns=['nota','Q38933','Q344873']):
        # TODO: add 'fecha' as second column and all symptoms
        super(CovidJsonParser, self).__init__()
        self.canonical_symptnames = {'Q38933':'fiebre','Q344873':'dificultad respiratoria'}
        self.symptcols = columns

    def as_csv_row(self, MedNote_file, sep="\t"):
        """Format JSON by MedNotesMiner to csv row of symptoms"""
        id_note = MedNote_file.split('/')[-1].split('.')[0]
        date = '17/04/2020 12:21'
        # read file and load json with symptoms
        with open(MedNote_file) as fp:
            json_object = json.load(fp, encoding='utf-8')        
        print(json.dumps(json_object, ensure_ascii=False, encoding='utf-8', indent=2))
        # detect presence/abscence of self.symptcols
        # for symptom in self.symptcols[1:]:
        #     name = self.canonical_symptnames[symptom]
        #     if symptom
        #return row

    def dir_to_csv(self, jsons_inputdir, csvtable_outputdir="./"):
        """Read a set of JSON by MedNotesMiner to form a symptoms table"""
        # header
        table = ','.join(self.columns)+'\n'

        # walk inputdir to get the csv rows
        for  MedNote in explore_dir(explore_dir, yield_extension='JSON'):
            r = self.as_csv_row(MedNote)
            table += r
        return table


if __name__ == '__main__':

    nota = "/Users/amolina/repo/covidminer/data/corte_SEDESA_22_abril_2020/Nota Médica_1587150149101.JSON"
    parser = CovidJsonParser()
    parser.as_csv_row(nota)
